# Creates a separate GitHub issue for a failing generated test classified
# as real_bug — a genuine defect the test caught deserves more durability
# than a PR comment (survives even if the PR is closed without the
# generated test being merged), per dev-notes/test-suggest.md. One issue
# per function: while it is open, further findings for the function go
# there as comments instead of a second issue (post_issue_once()).
create_bug_issue <- function(function_name, test_block, failure_message, classification) {
  title <- sprintf("Possible bug found by generated test: %s", function_name)
  body <- sprintf(
    paste(
      "A test generated by the test suggestion workflow failed against",
      "`%s`, and was classified as a likely genuine bug (not a bad test or",
      "environment issue):",
      "",
      "%s",
      "",
      "**Generated test:**",
      "```r",
      "%s",
      "```",
      "",
      "**Failure output:**",
      "```",
      "%s",
      "```",
      "",
      "This test was NOT committed — surfacing this issue for review is the",
      "only automatic action taken.",
      sep = "\n"
    ),
    function_name, classification$explanation, test_block, failure_message
  )

  post_issue_once(title, body, function_name)
}
