# Creates a separate GitHub issue for a failing generated test classified
# as real_bug — a genuine defect the test caught deserves more durability
# than a PR comment (survives even if the PR is closed without the
# generated test being merged), per docs/test-coverage-suggest.md.
create_bug_issue <- function(function_name, test_block, failure_message, classification) {
  title <- sprintf("Possible bug found by generated test: %s", function_name)
  body <- sprintf(
    paste(
      "A test generated by the test-coverage-suggest workflow failed against",
      "`%s`, and was classified as a likely genuine bug (not a bad test or",
      "environment issue):",
      "",
      "%s",
      "",
      "**Generated test:**",
      "```r",
      "%s",
      "```",
      "",
      "**Failure output:**",
      "```",
      "%s",
      "```",
      "",
      "This test was NOT committed — surfacing this issue for review is the",
      "only automatic action taken.",
      sep = "\n"
    ),
    function_name, classification$explanation, test_block, failure_message
  )

  post_github_json(
    sprintf("/repos/%s/issues", repo),
    list(title = title, body = body),
    function_name
  )
}
